steps:
  # Paso 1: Construir Tareas Pendientes
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tareas-pendientes:$COMMIT_SHA', 'TareasPendientes']
  
  # Paso 2: Construir Tareas Completadas
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tareas-completadas:$COMMIT_SHA', 'TareasCompletadas']

images:
  - 'gcr.io/$PROJECT_ID/tareas-pendientes:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tareas-completadas:$COMMIT_SHA'
