# docker-compose.yml
version: '3.8'

services:
  tareas-pendientes:
    build: 
      context: ./TareasPendient
      dockerfile: Dockerfile
    container_name: ms-tareas-pendientes
    volumes:
      - ./TareasPendient/tareas_pendientes.json:/app/tareas_pendientes.json
    networks:
      - tareas-network

  tareas-completadas:
    build:
      context: ./TareasCompleta
      dockerfile: Dockerfile
    container_name: ms-tareas-completadas
    volumes:
      - ./TareasCompleta/tareas_completas.json:/app/tareas_completas.json
    networks:
      - tareas-network
    
# Servidor web para la interfaz
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html  
      - ./nginx.conf:/etc/nginx/nginx.conf  
    networks:
      - tareas-network

networks:
  tareas-network:

    driver: bridge

